In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(tf.__version__)

1.10.1


In [85]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
raw_data_all = pd.read_csv('traindata_raw.csv', index_col=0)

In [12]:
raw_data_all.head()

0           1          2          3         4          5         6  \
0 -91.963967  105.096580 -30.380742  19.623144  7.864010  28.667215  9.144874   
1 -85.366237  101.649270 -33.703561  23.957620 -0.626421  25.965370  3.521350   
2 -70.602010   96.136897 -44.954211  22.478617 -5.727435  27.195755  4.279557   
3 -70.923855  100.204938 -48.644282  19.635599 -3.416086  28.776793  8.279170   
4 -72.968648  101.455395 -47.118626  16.485796 -4.556425  34.225432  9.645169   

          7          8         9  ...          31        32        33  \
0  8.710527   7.943736  3.226403  ...   -1.736931  0.362849  6.496445   
1  8.057379  12.864924  2.670274  ...   -5.326123 -4.981471  2.376308   
2  9.121658  15.989916  4.912378  ...   -5.221855 -5.024254  0.142265   
3  6.841322  16.674616  4.500598  ...   -5.981285 -4.582226  4.517435   
4  2.621069  14.869865  4.898435  ...   -7.666123 -7.110345  4.923937   

         34         35        36        37        38         39  label  
0 -2.391663 -11.616247 -9.043096 -7.675692 -5.406505   9.618369    voi  
1 -3.255108  -5.930639 -9.866653 -7.677595  0.697900  10.225007    voi  
2 -6.889198  -2.167274 -6.240126 -8.406016  1.081667   8.671729    voi  
3 -5.094420  -0.759547 -3.510984 -9.008126 -4.384427   5.054848    voi  
4 -2.876247  -4.629001 -7.439723 -9.067987 -6.983652   1.462925    voi  

[5 rows x 41 columns]

In [4]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(["voi", "vio", "tru", "sax", "pia", "org", "gel", "gac", "flu", "cla", "cel"])

LabelEncoder()

In [13]:
y_all = le.transform(raw_data_all['label'])
x_all = raw_data_all.drop(['label'],axis =1)

In [36]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x_all)
print(scaler.data_max_)
x_all_scaled = scaler.transform(x_all)
print(x_all_scaled)

[109.61838151 285.72876509 141.95353899 146.82711631  97.29848546
 100.66832546  77.17568385  69.72930732  67.60932858  75.83187842
  79.12927627  90.73181075  78.00221646  72.01479075  66.49828968
  79.34808801  81.57805319  81.65627243  68.54574713  88.77420663
  70.18624399  78.48115414  60.51033814  64.71805553  64.18162727
  65.62119707  63.73484468  60.48609441  56.56611649  65.20246844
  76.69662452  73.99370024  62.9391947   67.56181405  52.24818745
  52.85312824  65.35498964  65.20700908  67.7478285   61.94813725]
[[0.76329205 0.52181254 0.43886226 ... 0.37902533 0.41355379 0.55848558]
 [0.77103943 0.51268647 0.42804283 ... 0.37900911 0.46249013 0.56360389]
 [0.78837632 0.49809358 0.39140958 ... 0.37280283 0.46556662 0.55049863]
 ...
 [0.68577026 0.52850308 0.48033929 ... 0.48138761 0.40708729 0.46328231]
 [0.67922243 0.55801826 0.46962184 ... 0.47235934 0.41916292 0.42660999]
 [0.65649024 0.57141765 0.47877721 ... 0.46146527 0.47959007 0.44498139]]


In [34]:
scaler.transform(x_all)

(871650, 40)

In [37]:
from sklearn.model_selection import train_test_split
#Train_Test_Split得到训练集和测试集
x_train, x_test, y_train, y_test  = train_test_split(x_all_scaled, y_all, test_size = 0.1, random_state = 89)

In [39]:
train_set = np.array(x_train).reshape(784485, 1, 40)
train_label = np.array(y_train)
test_set = np.array(x_test).reshape(87165, 1, 40)
test_label = np.array(y_test)

In [40]:
train_set.shape

(784485, 1, 40)

In [41]:
len(train_label)

784485

In [42]:
test_set.shape

(87165, 1, 40)

In [43]:
train_set

array([[[0.78262429, 0.49057644, 0.61388665, ..., 0.43361695,
         0.48280001, 0.51645733]],

       [[0.85775929, 0.33186216, 0.51272962, ..., 0.55392075,
         0.54664866, 0.50176695]],

       [[0.80194414, 0.50511566, 0.48071963, ..., 0.40385252,
         0.41255284, 0.49535454]],

       ...,

       [[0.51788485, 0.78104154, 0.51238143, ..., 0.37899639,
         0.5174551 , 0.55353914]],

       [[0.74068903, 0.5930379 , 0.4377077 , ..., 0.48298273,
         0.18092639, 0.52902532]],

       [[0.71326946, 0.60884322, 0.55558095, ..., 0.34539109,
         0.49684364, 0.50179653]]])

In [87]:
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(train_label.reshape(-1,1))

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='ignore',
       n_values=None, sparse=True)

In [88]:
train_label_onehot = enc.transform(train_label.reshape(-1,1))

In [129]:
train_label_onehot.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]])

In [91]:
test_label_onehot = enc.transform(test_label.reshape(-1,1))

In [123]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(1, 40)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.tanh),
    keras.layers.Dense(64, activation=tf.nn.relu),
    keras.layers.Dense(64, activation=tf.nn.tanh),
    keras.layers.Dense(11, activation=tf.nn.softmax)
])

In [124]:
model.compile(optimizer=tf.train.AdamOptimizer(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [125]:
model.fit(train_set, train_label, epochs=10)

Epoch 1/10
784485/784485 [==============================] - 41s 52us/step - loss: 1.7839 - acc: 0.3870 1s - loss:
Epoch 2/10
784485/784485 [==============================] - 41s 52us/step - loss: 1.5991 - acc: 0.4549
Epoch 3/10
784485/784485 [==============================] - 41s 53us/step - loss: 1.5211 - acc: 0.4827A:
Epoch 4/10
784485/784485 [==============================] - 42s 53us/step - loss: 1.4798 - acc: 0.4975
Epoch 5/10
784485/784485 [==============================] - 43s 55us/step - loss: 1.4455 - acc: 0.5097 0s - loss: 1.4455 - 
Epoch 6/10
784485/784485 [==============================] - 44s 56us/step - loss: 1.4150 - acc: 0.5193
Epoch 7/10
784485/784485 [==============================] - 47s 60us/step - loss: 1.3891 - acc: 0.5291 7s - loss - ETA: 5s - loss: 1.3898 -  - ETA: 4s - loss: 1.38 -  - ETA: 0s - loss: 1.3892 - acc: 0.5
Epoch 8/10
784485/784485 [==============================] - 47s 59us/step - loss: 1.3645 - acc: 0.5378
Epoch 9/10
784485/784485 [================

In [103]:
pred_full = model.predict(test_set)

In [109]:
pred_full[:3]

array([[3.13714035e-02, 7.25069176e-03, 5.63760567e-03, 1.90432034e-02,
        5.60894728e-01, 5.72656244e-02, 5.53173653e-04, 1.25235632e-01,
        6.09396435e-02, 2.92775836e-02, 1.02530666e-01],
       [1.67146474e-01, 5.30439371e-04, 2.99736828e-04, 6.44245744e-03,
        1.18650362e-01, 2.58437485e-05, 1.89952576e-03, 7.73263024e-03,
        6.89056277e-01, 6.90427702e-03, 1.31202897e-03],
       [1.97654910e-04, 6.35374710e-02, 2.22683419e-02, 8.94161910e-02,
        1.13926234e-03, 1.29209633e-03, 2.19856836e-02, 7.90531874e-01,
        6.39198441e-03, 3.03420215e-03, 2.05301723e-04]], dtype=float32)

In [95]:
from __future__ import print_function
from keras.models import Sequential
import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv1D
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json
from keras import backend as K

model = Sequential()
model.add(Conv1D(32, (3), input_shape=(1,40), activation='relu', padding="same"))
model.add(Conv1D(32, (3), activation='relu', padding="same"))
model.add(Conv1D(32, (3), activation='relu', padding="same"))
model.add(Flatten())
model.add(Dense(64, activation='softmax'))
model.add(Dense(11, activation='softmax'))

model.compile(optimizer = tf.train.AdamOptimizer(),
              loss=keras.losses.categorical_crossentropy,
              metrics=['accuracy'])

In [97]:
batch_size = 128
epochs = 100
model.fit(train_set, train_label_onehot,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1)

Epoch 1/100
784485/784485 [==============================] - 17s 22us/step - loss: 2.2211 - acc: 0.1858
Epoch 2/100
784485/784485 [==============================] - 15s 19us/step - loss: 2.1277 - acc: 0.2232
Epoch 3/100
784485/784485 [==============================] - 15s 19us/step - loss: 2.0454 - acc: 0.2737
Epoch 4/100
784485/784485 [==============================] - 15s 19us/step - loss: 1.9403 - acc: 0.3267
Epoch 5/100
784485/784485 [==============================] - 15s 19us/step - loss: 1.8881 - acc: 0.3438
Epoch 6/100
784485/784485 [==============================] - 15s 19us/step - loss: 1.8491 - acc: 0.3586
Epoch 7/100
784485/784485 [==============================] - 21s 26us/step - loss: 1.8185 - acc: 0.3723
Epoch 8/100
784485/784485 [==============================] - 17s 22us/step - loss: 1.7897 - acc: 0.3849 1
Epoch 9/100
784485/784485 [==============================] - 15s 19us/step - loss: 1.7632 - acc: 0.3955
Epoch 10/100
784485/784485 [==============================] - 

KeyboardInterrupt: 

In [130]:
from __future__ import print_function
from keras.models import Sequential
import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv1D
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json
from keras import backend as K

model = Sequential()
model.add(Conv1D(32, (3), input_shape=(1,40), activation='relu', padding="same"))
model.add(Conv1D(32, (3), activation='relu', padding="same"))
model.add(Conv1D(32, (3), activation='relu', padding="same"))
model.add(Flatten())
model.add(Dense(64, activation='softmax'))
model.add(Dense(11, activation='softmax'))

model.compile(optimizer=keras.optimizers.SGD(lr=0.01),
              loss=keras.losses.categorical_crossentropy,
              metrics=['accuracy'])

In [131]:
batch_size = 128
epochs = 10
model.fit(train_set, train_label_onehot,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1)

Epoch 1/10
784485/784485 [==============================] - 27s 35us/step - loss: 2.3801 - acc: 0.1155
Epoch 2/10
784485/784485 [==============================] - 22s 28us/step - loss: 2.3781 - acc: 0.1160
Epoch 3/10
784485/784485 [==============================] - 24s 30us/step - loss: 2.3781 - acc: 0.1160
Epoch 4/10
784485/784485 [==============================] - 26s 33us/step - loss: 2.3781 - acc: 0.1160
Epoch 5/10
784485/784485 [==============================] - 23s 29us/step - loss: 2.3781 - acc: 0.1160
Epoch 6/10
784485/784485 [==============================] - 22s 28us/step - loss: 2.3781 - acc: 0.1160
Epoch 7/10
784485/784485 [==============================] - 22s 28us/step - loss: 2.3781 - acc: 0.1160
Epoch 8/10
784485/784485 [==============================] - 22s 28us/step - loss: 2.3781 - acc: 0.1160
Epoch 9/10
784485/784485 [==============================] - 24s 31us/step - loss: 2.3781 - acc: 0.1160 0s - loss: 2.3781 - acc: 0.11
Epoch 10/10
784485/784485 [================