In [1]:
import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display
import pandas as pd

In [2]:
import os
path = "IRMAS-Sample/Training" #文件夹目录
files= os.listdir(path)

In [4]:
instrument_type = 'vio'
rootpath = path +'/' +instrument_type
files = os.listdir(rootpath)

In [5]:
files

['134__[vio][nod][cla]2156__3.wav', '001__[vio][nod][cou_fol]2194__1.wav']

In [6]:
i = files[0]

In [10]:
j = files[1]

In [7]:
y, sr = librosa.load(rootpath+'/'+i)

In [85]:
y.shape

(66150,)

In [87]:
sr

22050

In [12]:
y1, sr1 = librosa.load(rootpath+'/'+j)

In [8]:
m_slaney = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40, dct_type=2)

In [13]:
m_slaney1 = librosa.feature.mfcc(y=y1, sr=sr1, n_mfcc=40, dct_type=2)

In [16]:
m_slaney.reshape(1,40,130)

array([[[-2.70335843e+02, -2.75138204e+02, -2.88807640e+02, ...,
         -2.96963268e+02, -2.83363670e+02, -2.75312490e+02],
        [ 1.54684387e+02,  1.49296606e+02,  1.51311208e+02, ...,
          1.56462013e+02,  1.65434769e+02,  1.58831721e+02],
        [-6.59523044e+01, -6.86358523e+01, -7.18963838e+01, ...,
         -5.55211597e+01, -4.88064769e+01, -3.63473564e+01],
        ...,
        [-4.57994084e-01, -2.07033805e+00, -5.19593899e+00, ...,
          1.66381445e+01,  2.00488841e+01,  1.67261973e+01],
        [ 7.12920606e+00,  9.27189477e+00,  3.72971079e+00, ...,
          1.75443985e+01,  8.02456515e+00, -2.96023035e+00],
        [-4.40376278e+00,  1.66784402e+00,  1.94882171e+00, ...,
          6.71812483e-01, -5.02444673e+00, -2.20493263e-02]]])

In [14]:
m_slaney1.shape

(40, 130)

In [19]:
m_slaney1

array([[-1.76857101e+02, -1.90790714e+02, -2.09507629e+02, ...,
        -1.81598756e+02, -1.71024424e+02, -1.48685316e+02],
       [ 1.22361403e+02,  1.14090577e+02,  1.09732853e+02, ...,
         1.29758018e+02,  1.19600712e+02,  1.07506742e+02],
       [ 6.05617054e+00, -6.62161010e+00, -2.83536499e+01, ...,
        -8.39186135e+00,  5.55746288e+00,  2.61251001e+01],
       ...,
       [ 1.77732934e+00, -7.05415213e-02, -7.45215255e+00, ...,
         7.83129957e+00,  8.76671972e+00,  6.36304508e+00],
       [-7.43321979e+00, -1.18997177e+01, -1.81902473e+01, ...,
         1.10857842e+01,  1.13337524e+01,  7.18139905e+00],
       [-3.29314325e+00, -6.07908177e+00, -1.18293140e+01, ...,
         9.02210991e+00,  1.01062058e+01,  6.88029825e+00]])

In [17]:
np.concatenate([m_slaney.reshape(1,40,130), m_slaney1.reshape(1,40,130)]).shape

(2, 40, 130)

In [51]:
def fileFolder2FeatureTable(instrument_type, path):
    rootpath = path +'/' +instrument_type
    files = os.listdir(rootpath)
    train_set_total = []
    train_label_total = []
    for i in files:
        y, sr = librosa.load(rootpath+'/'+i)
        m_slaney = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40, dct_type=2)
        #m_htk = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40, dct_type=3)
        #single_array = m_slaney.reshape(1,40,130)
        train_label_total.append(instrument_type)
        train_set_total.append(m_slaney)
        train_set_array = np.array(train_set_total)
    return (train_set_array, train_label_total)

In [52]:
voi_raw, voi_label = fileFolder2FeatureTable('voi','IRMAS-TrainingData')
vio_raw, vio_label = fileFolder2FeatureTable('vio','IRMAS-TrainingData')
tru_raw, tru_label = fileFolder2FeatureTable('tru','IRMAS-TrainingData')
sax_raw, sax_label = fileFolder2FeatureTable('sax','IRMAS-TrainingData')
pia_raw, pia_label = fileFolder2FeatureTable('pia','IRMAS-TrainingData')
org_raw, org_label = fileFolder2FeatureTable('org','IRMAS-TrainingData')
gel_raw, gel_label = fileFolder2FeatureTable('gel','IRMAS-TrainingData')
gac_raw, gac_label = fileFolder2FeatureTable('gac','IRMAS-TrainingData')
flu_raw, flu_label = fileFolder2FeatureTable('flu','IRMAS-TrainingData')
cla_raw, cla_label = fileFolder2FeatureTable('cla','IRMAS-TrainingData')
cel_raw, cel_label = fileFolder2FeatureTable('cel','IRMAS-TrainingData')

In [55]:
raw_data_all = np.concatenate([voi_raw, vio_raw, tru_raw, sax_raw, pia_raw, org_raw, gel_raw, gac_raw, flu_raw, cla_raw, cel_raw])

In [88]:
raw_data_all.shape

(6705, 40, 130)

In [92]:
import pickle
import h5py

In [93]:
h5f = h5py.File('data.h5', 'w')
h5f.create_dataset('dataset_1', data=raw_data_all)
h5f.close()

In [94]:
h5f1 = h5py.File('data.h5','r')

In [95]:
b = h5f1['dataset_1'][:]

In [97]:
h5f1.close()

In [98]:
np.allclose(raw_data_all,b)

True

In [59]:
label_all = voi_label + vio_label + tru_label + sax_label + pia_label + org_label + gel_label + gac_label + flu_label + cla_label + cel_label

In [60]:
len(label_all)

6705

In [106]:
label_all

['voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',
 'voi',


In [63]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(["voi", "vio", "tru", "sax", "pia", "org", "gel", "gac", "flu", "cla", "cel"])

LabelEncoder()

In [111]:
le.transform(['voi','vio'])

array([10,  9])

In [64]:
y_all = le.transform(label_all)

In [99]:
y_nparray = np.array(y_all)

In [100]:
y_nparray.shape

(6705,)

In [105]:
h5label = h5py.File('label.h5', 'w')
h5label.create_dataset('dataset_1', data=y_nparray)
h5label.close()

In [65]:
from sklearn.model_selection import train_test_split
#Train_Test_Split得到训练集和测试集
x_train, x_test, y_train, y_test  = train_test_split(raw_data_all, y_all, test_size = 0.1, random_state = 89)

In [66]:
x_train.shape

(6034, 40, 130)

In [62]:
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)

1.10.1


In [67]:
#测试全连接网络
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(40, 130)),
    keras.layers.Dense(256)
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(64, activation=tf.nn.relu),
    keras.layers.Dense(11, activation=tf.nn.softmax)
])
model.compile(optimizer=tf.train.AdamOptimizer(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
6034/6034 [==============================] - 1s 220us/step - loss: 14.7208 - acc: 0.0863
Epoch 2/10
6034/6034 [==============================] - 1s 127us/step - loss: 14.7371 - acc: 0.0857
Epoch 3/10
6034/6034 [==============================] - 1s 120us/step - loss: 14.7371 - acc: 0.0857
Epoch 4/10
6034/6034 [==============================] - 1s 127us/step - loss: 14.7371 - acc: 0.0857
Epoch 5/10
6034/6034 [==============================] - 1s 121us/step - loss: 14.7371 - acc: 0.0857
Epoch 6/10
6034/6034 [==============================] - 1s 120us/step - loss: 14.7371 - acc: 0.0857
Epoch 7/10
6034/6034 [==============================] - 1s 128us/step - loss: 14.7371 - acc: 0.0857
Epoch 8/10
6034/6034 [==============================] - 1s 122us/step - loss: 14.7371 - acc: 0.0857
Epoch 9/10
6034/6034 [==============================] - 1s 121us/step - loss: 14.7371 - acc: 0.0857
Epoch 10/10
6034/6034 [==============================] - 1s 121us/step - loss: 14.7371 - acc: 0.0857

In [113]:
#测试CNN
from __future__ import print_function
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv1D
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json
from keras import backend as K

model = Sequential()
model.add(Conv1D(64,(1), input_shape=(40,130), activation='relu', padding="same"))
model.add(Conv1D(64,(1), activation='relu', padding="same"))
model.add(Conv1D(64,(1), activation='relu', padding="same"))
model.add(Flatten())
model.add(Dense(64, activation='softmax'))
model.add(Dense(11, activation='softmax'))

model.compile(optimizer = tf.train.AdamOptimizer(),
              loss='sparse_categorical_crossentropy', #keras.losses.categorical_crossentropy,
              metrics=['accuracy'])
batch_size = 128
epochs = 10
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1)

Epoch 1/10
6034/6034 [==============================] - 4s 647us/step - loss: 2.3744 - acc: 0.1130
Epoch 2/10
6034/6034 [==============================] - 1s 200us/step - loss: 2.3669 - acc: 0.1376
Epoch 3/10
6034/6034 [==============================] - 1s 201us/step - loss: 2.3473 - acc: 0.1533
Epoch 4/10
6034/6034 [==============================] - 1s 231us/step - loss: 2.3304 - acc: 0.1553
Epoch 5/10
6034/6034 [==============================] - 1s 229us/step - loss: 2.3381 - acc: 0.1463
Epoch 6/10
6034/6034 [==============================] - 1s 228us/step - loss: 2.3089 - acc: 0.1608
Epoch 7/10
6034/6034 [==============================] - 1s 236us/step - loss: 2.3157 - acc: 0.1564
Epoch 8/10
6034/6034 [==============================] - 1s 213us/step - loss: 2.3063 - acc: 0.1545
Epoch 9/10
6034/6034 [==============================] - 2s 259us/step - loss: 2.3163 - acc: 0.1488
Epoch 10/10
6034/6034 [==============================] - 1s 235us/step - loss: 2.2925 - acc: 0.1692


In [114]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv1D, MaxPooling1D
model = Sequential()
model.add(Conv1D(32, (5), padding='same',
                 input_shape=(40,130)))
model.add(Activation('relu'))
model.add(Conv1D(32, (5)))
model.add(Activation('relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))

model.add(Conv1D(64, (3), padding='same'))
model.add(Activation('relu'))
model.add(Conv1D(64, (3)))
model.add(Activation('relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(11))
model.add(Activation('softmax'))
model.compile(optimizer = tf.train.AdamOptimizer(),
              loss='sparse_categorical_crossentropy', #keras.losses.categorical_crossentropy,
              metrics=['accuracy'])
batch_size = 128
epochs = 10
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1)

Epoch 1/10
6034/6034 [==============================] - 4s 714us/step - loss: 4.2029 - acc: 0.1102
Epoch 2/10
6034/6034 [==============================] - 3s 569us/step - loss: 2.3613 - acc: 0.1429
Epoch 3/10
6034/6034 [==============================] - 4s 586us/step - loss: 2.3037 - acc: 0.1823 1s 
Epoch 4/10
6034/6034 [==============================] - 4s 592us/step - loss: 2.2454 - acc: 0.1992
Epoch 5/10
6034/6034 [==============================] - 3s 556us/step - loss: 2.1678 - acc: 0.2443
Epoch 6/10
6034/6034 [==============================] - 3s 571us/step - loss: 2.1161 - acc: 0.2557
Epoch 7/10
6034/6034 [==============================] - 4s 602us/step - loss: 2.0988 - acc: 0.2686
Epoch 8/10
6034/6034 [==============================] - 4s 610us/step - loss: 2.0702 - acc: 0.2753
Epoch 9/10
6034/6034 [==============================] - 4s 606us/step - loss: 2.0167 - acc: 0.2932
Epoch 10/10
6034/6034 [==============================] - 3s 574us/step - loss: 1.9902 - acc: 0.3028
